// Sample dataset of free LLM/AI API access routes, modeled after freellm.sh.
// This is invented sample data for the demo — not live-scraped.

export type Modality =
  | "chat"
  | "embeddings"
  | "image"
  | "tts"
  | "stt"
  | "vision"
  | "code";

export type Access = "no-signup" | "api-key" | "card-required";

export interface Endpoint {
  id: string;
  name: string;
  provider: string;
  models: string[];
  modality: Modality;
  access: Access;
  limits: string;
  license: string;
  baseUrl: string;
  openaiCompatible: boolean;
  status: "operational" | "degraded" | "unverified";
  notes: string;
  lastVerified: string;
}

export const ENDPOINTS: Endpoint[] = [
  {
    id: "openrouter-free-pool",
    name: "OpenRouter :free pool",
    provider: "OpenRouter",
    models: ["llama-3.3-70b:free", "gemma-3-27b:free", "qwen3-32b:free", "mistral-small-3.1:free"],
    modality: "chat",
    access: "api-key",
    limits: "50 req/day shared across all :free models; 20 req/min",
    license: "Varies per model",
    baseUrl: "https://openrouter.ai/api/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "Single API key unlocks every model tagged :free. Daily cap is shared across the pool, so heavy use of one model exhausts the others.",
    lastVerified: "2026-09-12",
  },
  {
    id: "groq-free-tier",
    name: "Groq free tier",
    provider: "Groq",
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b"],
    modality: "chat",
    access: "api-key",
    limits: "30 RPM, 14,400 req/day on llama-3.1-8b; lower caps on 70B",
    license: "Llama Community License",
    baseUrl: "https://api.groq.com/openai/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "LPU-backed inference, consistently the fastest free tokens available. No card required for the free tier.",
    lastVerified: "2026-09-13",
  },
  {
    id: "gemini-api-free",
    name: "Gemini API free tier",
    provider: "Google",
    models: ["gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.0-flash"],
    modality: "chat",
    access: "api-key",
    limits: "10 RPM / 250 req/day on 2.5-flash; 15 RPM / 1,000 req/day on flash-lite",
    license: "Proprietary",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    openaiCompatible: true,
    status: "operational",
    notes: "Free tier via AI Studio key. Prompts may be used for training on the free tier — avoid sensitive data.",
    lastVerified: "2026-09-13",
  },
  {
    id: "mistral-la-plateforme",
    name: "La Plateforme experiment tier",
    provider: "Mistral",
    models: ["mistral-small-latest", "open-mistral-nemo", "codestral-latest"],
    modality: "chat",
    access: "api-key",
    limits: "1 req/sec, 500K tokens/min, 1B tokens/month",
    license: "Apache 2.0 (open models)",
    baseUrl: "https://api.mistral.ai/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "Generous free 'experiment' plan; requires phone verification but no card. Data used for training unless you opt out.",
    lastVerified: "2026-09-11",
  },
  {
    id: "cerebras-trial",
    name: "Cerebras trial credits",
    provider: "Cerebras",
    models: ["llama-3.3-70b", "llama-3.1-8b", "qwen-3-32b"],
    modality: "chat",
    access: "card-required",
    limits: "$5 credits for 30 days after verified card; 5 RPM, 1M tokens/day on trial",
    license: "Llama Community License",
    baseUrl: "https://api.cerebras.ai/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "Wafer-scale inference, extremely high tokens/sec. No permanently free tier — trial only.",
    lastVerified: "2026-09-10",
  },
  {
    id: "cohere-trial",
    name: "Cohere trial keys",
    provider: "Cohere",
    models: ["command-r7b", "command-r-plus", "embed-v4"],
    modality: "chat",
    access: "api-key",
    limits: "20 RPM, 1,000 req/month per trial key",
    license: "CC-BY-NC (weights), API proprietary",
    baseUrl: "https://api.cohere.ai/v2",
    openaiCompatible: false,
    status: "operational",
    notes: "Trial keys never expire but are rate-limited and for non-production use. Includes embeddings and rerank.",
    lastVerified: "2026-09-09",
  },
  {
    id: "hf-inference-free",
    name: "HF Inference Providers free quota",
    provider: "Hugging Face",
    models: ["llama-3.2-3b", "qwen3-8b", "flux.1-schnell", "whisper-large-v3"],
    modality: "chat",
    access: "api-key",
    limits: "~$0.10/month of free inference credits per account",
    license: "Varies per model",
    baseUrl: "https://router.huggingface.co/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "Small monthly credit works across chat, image, and audio providers routed through one endpoint.",
    lastVerified: "2026-09-12",
  },
  {
    id: "pollinations-text",
    name: "Pollinations text API",
    provider: "Pollinations",
    models: ["openai-fast", "mistral", "llama-roblox"],
    modality: "chat",
    access: "no-signup",
    limits: "Anonymous: ~1 req/3s; no hard daily cap published",
    license: "Open source (MIT platform)",
    baseUrl: "https://text.pollinations.ai",
    openaiCompatible: true,
    status: "operational",
    notes: "Genuinely anonymous — no key, no signup. GET or OpenAI-style POST. Ad-supported; responses may include a referral line.",
    lastVerified: "2026-09-14",
  },
  {
    id: "pollinations-image",
    name: "Pollinations image API",
    provider: "Pollinations",
    models: ["flux", "turbo", "gptimage"],
    modality: "image",
    access: "no-signup",
    limits: "Anonymous: ~1 image/5s per IP",
    license: "Open source (MIT platform)",
    baseUrl: "https://image.pollinations.ai",
    openaiCompatible: false,
    status: "operational",
    notes: "URL-based image generation: /prompt/{text} returns a JPEG. No key needed; great for demos.",
    lastVerified: "2026-09-14",
  },
  {
    id: "together-free-models",
    name: "Together free models",
    provider: "Together AI",
    models: ["llama-3.3-70b-free", "flux.1-schnell-free", "deepseek-r1-distill-70b-free"],
    modality: "chat",
    access: "api-key",
    limits: "Free-tagged models: 60 req/min shared; reduced priority at peak",
    license: "Varies per model",
    baseUrl: "https://api.together.xyz/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "A rotating set of models is offered free with reduced priority. $1 signup credit on top.",
    lastVerified: "2026-09-08",
  },
  {
    id: "sambanova-free",
    name: "SambaNova Cloud free tier",
    provider: "SambaNova",
    models: ["llama-3.3-70b", "deepseek-r1", "qwen3-32b"],
    modality: "chat",
    access: "api-key",
    limits: "30 RPM on 8B–32B models, 10 RPM on 70B+",
    license: "Llama Community License",
    baseUrl: "https://api.sambanova.ai/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "RDU-accelerated inference; free tier is genuinely free with no card, aimed at developers.",
    lastVerified: "2026-09-07",
  },
  {
    id: "cloudflare-workers-ai",
    name: "Workers AI free allocation",
    provider: "Cloudflare",
    models: ["llama-3.1-8b", "whisper", "bge-base-en", "flux-1-schnell"],
    modality: "chat",
    access: "api-key",
    limits: "10,000 neurons/day free (~100–300 chat responses)",
    license: "Varies per model",
    baseUrl: "https://api.cloudflare.com/client/v4/accounts/{id}/ai",
    openaiCompatible: true,
    status: "operational",
    notes: "Neuron-based metering across chat, embeddings, image, and audio models at the edge.",
    lastVerified: "2026-09-11",
  },
  {
    id: "github-models",
    name: "GitHub Models playground",
    provider: "GitHub",
    models: ["gpt-4o-mini", "llama-3.3-70b", "phi-4", "deepseek-r1"],
    modality: "chat",
    access: "api-key",
    limits: "15 RPM / 150 req/day (low tier); 8K in / 4K out tokens per request",
    license: "Proprietary / varies",
    baseUrl: "https://models.github.ai/inference",
    openaiCompatible: true,
    status: "operational",
    notes: "Free for anyone with a GitHub account via PAT. Meant for prototyping; hard token caps per request.",
    lastVerified: "2026-09-13",
  },
  {
    id: "nvidia-nim",
    name: "NVIDIA NIM trial credits",
    provider: "NVIDIA",
    models: ["llama-3.3-70b", "nemotron-70b", "deepseek-r1"],
    modality: "chat",
    access: "api-key",
    limits: "1,000 free inference credits on signup (1 credit ≈ 1 request)",
    license: "NVIDIA AI Foundation License",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "build.nvidia.com hosts dozens of models behind one OpenAI-compatible endpoint. Credits refresh for developer program members.",
    lastVerified: "2026-09-06",
  },
  {
    id: "zenmux-free-routes",
    name: "Zenmux $0 routes",
    provider: "Zenmux",
    models: ["sapiens-ai/agnes-2.5-flash", "atria-asi/atria-dawn-preview"],
    modality: "chat",
    access: "api-key",
    limits: "$0/M tokens on selected preview models; fair-use throttling",
    license: "Proprietary (preview)",
    baseUrl: "https://api.zenmux.io/v1",
    openaiCompatible: true,
    status: "unverified",
    notes: "Preview models are free while providers collect eval data. Routes appear and disappear weekly.",
    lastVerified: "2026-09-05",
  },
  {
    id: "orcarouter-free",
    name: "OrcaRouter $0 requests",
    provider: "OrcaRouter",
    models: ["orca-chat-mini", "orca-coder-7b"],
    modality: "chat",
    access: "api-key",
    limits: "$0 per request on tagged models; 10 RPM",
    license: "Proprietary",
    baseUrl: "https://api.orcarouter.dev/v1",
    openaiCompatible: true,
    status: "degraded",
    notes: "Aggregator with a small free lane. Frequent 429s at peak hours; retry with backoff.",
    lastVerified: "2026-09-04",
  },
  {
    id: "selfhost-chat-pool",
    name: "Self-hosted chat pool",
    provider: "freeLLM community",
    models: ["qwen3-14b", "gemma-3-12b"],
    modality: "chat",
    access: "no-signup",
    limits: "Anon ~2.5K–6K tokens/day; email signup 30K/day, no card",
    license: "MIT",
    baseUrl: "https://pool.example-freellm.sh/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "Shared daily token pool. POST /v1/chat/ verified working without a key; a 1-word call consumed ~1.5K tokens with the system prompt.",
    lastVerified: "2026-09-14",
  },
  {
    id: "selfhost-tts",
    name: "Self-hosted TTS pool",
    provider: "freeLLM community",
    models: ["kokoro-82m", "piper-voices"],
    modality: "tts",
    access: "no-signup",
    limits: "~100 tokens per call (1 token / 4 chars); uncapped within daily pool",
    license: "Apache 2.0",
    baseUrl: "https://pool.example-freellm.sh/v1/audio/speech",
    openaiCompatible: true,
    status: "operational",
    notes: "Fast neural TTS from the shared pool. Multiple voices; streaming supported.",
    lastVerified: "2026-09-14",
  },
  {
    id: "selfhost-stt",
    name: "Self-hosted STT (Whisper)",
    provider: "freeLLM community",
    models: ["whisper-large-v3-turbo"],
    modality: "stt",
    access: "no-signup",
    limits: "~500 tokens/minute of audio; shared daily token pool",
    license: "MIT",
    baseUrl: "https://pool.example-freellm.sh/v1/audio/transcriptions",
    openaiCompatible: true,
    status: "operational",
    notes: "Drop-in replacement for OpenAI transcription endpoint. 25MB file cap.",
    lastVerified: "2026-09-13",
  },
  {
    id: "selfhost-image",
    name: "Self-hosted image gen",
    provider: "freeLLM community",
    models: ["flux.1-schnell", "sdxl-turbo"],
    modality: "image",
    access: "no-signup",
    limits: "~1,000 tokens/image; free accounts capped at 5 images/day",
    license: "Apache 2.0",
    baseUrl: "https://pool.example-freellm.sh/v1/images/generations",
    openaiCompatible: true,
    status: "operational",
    notes: "Shared 30K/day signup pool. 1024px max on the free lane.",
    lastVerified: "2026-09-12",
  },
  {
    id: "selfhost-embeddings",
    name: "Self-hosted embeddings (bge-m3)",
    provider: "freeLLM community",
    models: ["bge-m3", "nomic-embed-text-v2"],
    modality: "embeddings",
    access: "no-signup",
    limits: "Shared daily token pool; batches up to 96 inputs",
    license: "MIT",
    baseUrl: "https://pool.example-freellm.sh/v1/embeddings",
    openaiCompatible: true,
    status: "operational",
    notes: "Multilingual dense + sparse embeddings. Ideal free option for small RAG demos.",
    lastVerified: "2026-09-13",
  },
  {
    id: "selfhost-rmbg",
    name: "Self-hosted background removal",
    provider: "freeLLM community",
    models: ["rmbg-2.0"],
    modality: "vision",
    access: "no-signup",
    limits: "~500 tokens/image; shared daily token pool",
    license: "Apache 2.0",
    baseUrl: "https://pool.example-freellm.sh/v1/images/rmbg",
    openaiCompatible: false,
    status: "operational",
    notes: "Returns a transparent PNG. Popular enough that the pool drains by evening UTC.",
    lastVerified: "2026-09-11",
  },
  {
    id: "opencode-zen",
    name: "OpenCode Zen stealth model",
    provider: "OpenCode",
    models: ["zen-stealth"],
    modality: "code",
    access: "api-key",
    limits: "Free for a limited time; usable only inside OpenCode",
    license: "Proprietary (stealth)",
    baseUrl: "n/a (client-integrated)",
    openaiCompatible: false,
    status: "unverified",
    notes: "Stealth frontier code model, free while in eval. Data may be used to improve the model. Not a public anonymous API.",
    lastVerified: "2026-09-10",
  },
  {
    id: "mistral-codestral-free",
    name: "Codestral free endpoint",
    provider: "Mistral",
    models: ["codestral-2501"],
    modality: "code",
    access: "api-key",
    limits: "30 RPM, 2,000 req/day on the dedicated codestral endpoint",
    license: "MNPL (non-production)",
    baseUrl: "https://codestral.mistral.ai/v1",
    openaiCompatible: true,
    status: "operational",
    notes: "Separate free endpoint for IDE integrations — FIM completion + chat. Phone verification, no card.",
    lastVerified: "2026-09-09",
  },
  {
    id: "google-embeddings-free",
    name: "Gemini embeddings free tier",
    provider: "Google",
    models: ["gemini-embedding-001"],
    modality: "embeddings",
    access: "api-key",
    limits: "100 RPM, 30,000 tokens/min, 1,000 req/day",
    license: "Proprietary",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    openaiCompatible: true,
    status: "operational",
    notes: "3072-dim embeddings with Matryoshka truncation. Same AI Studio key as the chat tier.",
    lastVerified: "2026-09-13",
  },
  {
    id: "groq-whisper",
    name: "Groq Whisper transcription",
    provider: "Groq",
    models: ["whisper-large-v3", "whisper-large-v3-turbo"],
    modality: "stt",
    access: "api-key",
    limits: "20 req/min, 2,000 req/day, 28,800 audio-seconds/day",
    license: "MIT (weights)",
    baseUrl: "https://api.groq.com/openai/v1/audio/transcriptions",
    openaiCompatible: true,
    status: "operational",
    notes: "Transcribes ~10 minutes of audio in seconds. Same free key as Groq chat.",
    lastVerified: "2026-09-13",
  },
  {
    id: "deepinfra-trial",
    name: "DeepInfra signup credit",
    provider: "DeepInfra",
    models: ["llama-3.3-70b", "qwen3-235b-a22b", "flux-1-dev"],
    modality: "chat",
    access: "api-key",
    limits: "$1.80 free credit on signup; pay-as-you-go after",
    license: "Varies per model",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    openaiCompatible: true,
    status: "operational",
    notes: "Credit does not expire. Cheap per-token pricing makes the credit last a long time on small models.",
    lastVerified: "2026-09-05",
  },
  {
    id: "clawlabs-json",
    name: "clawlabs free-models JSON",
    provider: "ClawLabs",
    models: ["(index of OpenRouter :free + Pollinations)"],
    modality: "chat",
    access: "no-signup",
    limits: "Static JSON, no rate limit; updated daily",
    license: "CC0 (data)",
    baseUrl: "https://raw.clawlabs.dev/free-ai-models.json",
    openaiCompatible: false,
    status: "operational",
    notes: "Not an inference endpoint — a live machine-readable index of free routes, updated 2026-09-14. Useful for building tools like this one.",
    lastVerified: "2026-09-14",
  },
  {
    id: "lambda-trial",
    name: "Lambda Inference trial",
    provider: "Lambda",
    models: ["llama-3.3-70b", "hermes-3-405b"],
    modality: "chat",
    access: "card-required",
    limits: "$10 credit with verified card; standard rate limits",
    license: "Llama Community License",
    baseUrl: "https://api.lambda.ai/v1",
    openaiCompatible: true,
    status: "unverified",
    notes: "Serverless per-token pricing on big open models. Trial credit only — no permanent free lane.",
    lastVerified: "2026-09-02",
  },
  {
    id: "selfhost-music",
    name: "Self-hosted music gen",
    provider: "freeLLM community",
    models: ["ace-step-v1"],
    modality: "tts",
    access: "no-signup",
    limits: "~5,000 tokens/track; free accounts capped at 2 songs/day",
    license: "Apache 2.0",
    baseUrl: "https://pool.example-freellm.sh/v1/audio/music",
    openaiCompatible: false,
    status: "operational",
    notes: "Full-track generation with lyrics conditioning. Queue times spike on weekends.",
    lastVerified: "2026-09-12",
  },
  {
    id: "selfhost-video",
    name: "Self-hosted video gen",
    provider: "freeLLM community",
    models: ["wan-2.2-t2v"],
    modality: "image",
    access: "no-signup",
    limits: "~15,000 tokens/clip; free accounts capped at 1 video/day",
    license: "Apache 2.0",
    baseUrl: "https://pool.example-freellm.sh/v1/video/generations",
    openaiCompatible: false,
    status: "degraded",
    notes: "5-second 720p clips. The single daily slot goes fast; queue opens 00:00 UTC.",
    lastVerified: "2026-09-10",
  },
  {
    id: "selfhost-stems",
    name: "Self-hosted stem splitter",
    provider: "freeLLM community",
    models: ["demucs-v4"],
    modality: "stt",
    access: "no-signup",
    limits: "~500 tokens/track; shared daily token pool",
    license: "MIT",
    baseUrl: "https://pool.example-freellm.sh/v1/audio/stems",
    openaiCompatible: false,
    status: "operational",
    notes: "Splits a track into vocals/drums/bass/other. 10-minute file cap.",
    lastVerified: "2026-09-11",
  },
  {
    id: "selfhost-image-edit",
    name: "Self-hosted image edit",
    provider: "freeLLM community",
    models: ["flux-kontext-dev"],
    modality: "image",
    access: "no-signup",
    limits: "Free accounts capped at 5 image edits/day; shared daily pool",
    license: "MIT",
    baseUrl: "https://pool.example-freellm.sh/v1/images/edits",
    openaiCompatible: true,
    status: "operational",
    notes: "Instruction-based editing (\"make the sky pink\"). Masks supported via multipart upload.",
    lastVerified: "2026-09-12",
  },
];

export const MODALITY_LABELS: Record<Modality, string> = {
  chat: "Chat / LLM",
  embeddings: "Embeddings",
  image: "Image / Video",
  tts: "Speech / Audio out",
  stt: "Audio in / Transcribe",
  vision: "Vision",
  code: "Code",
};

export const ACCESS_LABELS: Record<Access, string> = {
  "no-signup": "No signup",
  "api-key": "Free API key",
  "card-required": "Card required",
};
