// Curated SAMPLE dataset modeled on the kind of entries the Inspo MCP archive
// returns (site + DESIGN.md-style notes). All palette/font data is illustrative.

export interface Screen {
  id: string;
  name: string;
  url: string;
  tagline: string;
  category: string;
  layout: "marquee-hero" | "bento-grid" | "split-studio" | "dashboard" | "editorial";
  palette: string[]; // 5 hex colors: bg, surface, text, accent, accent-2
  fonts: { display: string; body: string };
  tags: string[];
  keywords: string[];
}

export const SCREENS: Screen[] = [
  {
    id: "linear",
    name: "Linear",
    url: "linear.app",
    tagline: "Plan and build products",
    category: "dev tools",
    layout: "marquee-hero",
    palette: ["#08090d", "#141620", "#f7f8f8", "#5e6ad2", "#8a8f98"],
    fonts: { display: "Inter Display", body: "Inter" },
    tags: ["dark", "minimal", "product", "saas", "gradient"],
    keywords: ["issue tracking", "software", "startup", "sleek", "purple", "developer", "b2b", "roadmap"],
  },
  {
    id: "vercel",
    name: "Vercel",
    url: "vercel.com",
    tagline: "Your complete platform for the web",
    category: "dev tools",
    layout: "bento-grid",
    palette: ["#000000", "#111111", "#fafafa", "#0070f3", "#ff0080"],
    fonts: { display: "Geist", body: "Geist" },
    tags: ["dark", "technical", "bold", "monochrome", "saas"],
    keywords: ["deploy", "infrastructure", "developer", "triangle", "high contrast", "b2b", "platform"],
  },
  {
    id: "stripe-press",
    name: "Stripe Press",
    url: "press.stripe.com",
    tagline: "Ideas for progress",
    category: "editorial",
    layout: "editorial",
    palette: ["#f6f5f1", "#ffffff", "#1a1a1a", "#635bff", "#e8a87c"],
    fonts: { display: "Tiempos Headline", body: "Söhne" },
    tags: ["editorial", "elegant", "serif", "light", "print-inspired"],
    keywords: ["books", "publishing", "literary", "premium", "reading", "typography", "classic"],
  },
  {
    id: "raycast",
    name: "Raycast",
    url: "raycast.com",
    tagline: "Your shortcut to everything",
    category: "productivity",
    layout: "marquee-hero",
    palette: ["#0a0a0a", "#1a1420", "#f5f5f5", "#ff6363", "#59d499"],
    fonts: { display: "Inter Display", body: "Inter" },
    tags: ["dark", "playful", "product", "glow", "keyboard"],
    keywords: ["launcher", "mac", "developer", "productivity", "neon", "fast", "shortcuts"],
  },
  {
    id: "daybridge",
    name: "Daybridge",
    url: "daybridge.com",
    tagline: "A calmer kind of calendar",
    category: "productivity",
    layout: "split-studio",
    palette: ["#fdfcfa", "#f3efe9", "#22261f", "#3a5a40", "#d4a373"],
    fonts: { display: "Gambetta", body: "General Sans" },
    tags: ["calm", "warm", "light", "minimal", "friendly"],
    keywords: ["calendar", "planning", "cozy", "soft", "organic", "wellness", "gentle", "consumer"],
  },
  {
    id: "hex",
    name: "Hex",
    url: "hex.tech",
    tagline: "AI analytics for your whole team",
    category: "data",
    layout: "bento-grid",
    palette: ["#f7f5f2", "#ffffff", "#191a23", "#473982", "#f5c518"],
    fonts: { display: "Reckless Neue", body: "Matter" },
    tags: ["light", "editorial", "data", "saas", "serif"],
    keywords: ["analytics", "notebook", "dashboard", "charts", "ai", "b2b", "collaboration", "fintech"],
  },
  {
    id: "aave",
    name: "Aave",
    url: "aave.com",
    tagline: "The liquidity protocol",
    category: "fintech",
    layout: "marquee-hero",
    palette: ["#0f1020", "#1b1d33", "#f1f1f6", "#b6509e", "#2ebac6"],
    fonts: { display: "Space Grotesk", body: "Inter" },
    tags: ["dark", "gradient", "crypto", "futuristic", "fintech"],
    keywords: ["defi", "finance", "protocol", "web3", "money", "lending", "glow", "trust"],
  },
  {
    id: "sanity",
    name: "Sanity",
    url: "sanity.io",
    tagline: "The content operating system",
    category: "dev tools",
    layout: "split-studio",
    palette: ["#ffffff", "#f6f6f8", "#101112", "#f03e2f", "#2276fc"],
    fonts: { display: "Inter Display", body: "Inter" },
    tags: ["light", "technical", "bold", "structured", "saas"],
    keywords: ["cms", "content", "developer", "api", "red", "swiss", "b2b", "clean"],
  },
  {
    id: "ghost",
    name: "Ghost",
    url: "ghost.org",
    tagline: "Independent publishing",
    category: "editorial",
    layout: "editorial",
    palette: ["#15171a", "#222428", "#f8f8f8", "#30cf43", "#ffb41f"],
    fonts: { display: "Inter Tight", body: "Inter" },
    tags: ["dark", "editorial", "bold", "publishing", "creator"],
    keywords: ["blog", "newsletter", "writers", "membership", "magazine", "media", "indie"],
  },
  {
    id: "tracebit",
    name: "Tracebit",
    url: "tracebit.com",
    tagline: "Security canaries for the cloud",
    category: "security",
    layout: "marquee-hero",
    palette: ["#0b0e14", "#151a24", "#e8ecf1", "#ffc53d", "#4f6df5"],
    fonts: { display: "PP Mori", body: "Inter" },
    tags: ["dark", "technical", "serious", "enterprise", "minimal"],
    keywords: ["security", "cloud", "detection", "b2b", "trust", "infrastructure", "amber"],
  },
  {
    id: "amie",
    name: "Amie",
    url: "amie.so",
    tagline: "The joyful productivity app",
    category: "productivity",
    layout: "marquee-hero",
    palette: ["#ffffff", "#f6f4ff", "#17151f", "#8b5cf6", "#fb7185"],
    fonts: { display: "GT Walsheim", body: "GT Walsheim" },
    tags: ["playful", "light", "colorful", "rounded", "consumer"],
    keywords: ["calendar", "todo", "fun", "joyful", "bubbly", "emoji", "candy", "friendly"],
  },
  {
    id: "gumroad",
    name: "Gumroad",
    url: "gumroad.com",
    tagline: "Go from zero to $1",
    category: "commerce",
    layout: "editorial",
    palette: ["#ffffff", "#f4f4f0", "#000000", "#ff90e8", "#ffc900"],
    fonts: { display: "ABC Favorit", body: "ABC Favorit" },
    tags: ["brutalist", "bold", "colorful", "playful", "high-contrast"],
    keywords: ["creator", "commerce", "sell", "loud", "pink", "borders", "flat", "indie", "shop"],
  },
  {
    id: "mercury",
    name: "Mercury",
    url: "mercury.com",
    tagline: "Banking for ambitious companies",
    category: "fintech",
    layout: "split-studio",
    palette: ["#f8f9fb", "#ffffff", "#1e2029", "#5266eb", "#a8b3cf"],
    fonts: { display: "Circular", body: "Circular" },
    tags: ["calm", "light", "elegant", "fintech", "trustworthy"],
    keywords: ["banking", "finance", "startup", "professional", "airy", "premium", "dashboard", "b2b"],
  },
  {
    id: "family",
    name: "Family",
    url: "family.co",
    tagline: "The everything wallet",
    category: "fintech",
    layout: "marquee-hero",
    palette: ["#ffffff", "#f7f7f7", "#111111", "#3b82f6", "#fbbf24"],
    fonts: { display: "SF Pro Display", body: "SF Pro" },
    tags: ["playful", "light", "consumer", "rounded", "delightful"],
    keywords: ["wallet", "crypto", "mobile", "app", "animation", "friendly", "ethereum", "smooth"],
  },
  {
    id: "arc",
    name: "Arc (Browser Co.)",
    url: "arc.net",
    tagline: "A browser that browses with you",
    category: "consumer",
    layout: "split-studio",
    palette: ["#fceff2", "#ffffff", "#2e2a35", "#e6395c", "#7c5cff"],
    fonts: { display: "Olympic Serif", body: "Basel Grotesk" },
    tags: ["playful", "colorful", "consumer", "quirky", "editorial"],
    keywords: ["browser", "whimsical", "gradient", "pastel", "personality", "fun", "creative"],
  },
  {
    id: "resend",
    name: "Resend",
    url: "resend.com",
    tagline: "Email for developers",
    category: "dev tools",
    layout: "dashboard",
    palette: ["#0a0a0a", "#151515", "#ededed", "#ffffff", "#666666"],
    fonts: { display: "Inter Display", body: "Inter" },
    tags: ["dark", "minimal", "monochrome", "technical", "sleek"],
    keywords: ["email", "api", "developer", "black", "grayscale", "b2b", "console", "dashboard"],
  },
];
